NUMPY

In [1]:
import numpy as np

In [4]:
n1=np.array([10,20,30])
print(n1)

[10 20 30]


In [6]:
l1=[10,30,405,506]
x=np.array(l1)
print(x)

[ 10  30 405 506]


In [7]:
print(type(x))

<class 'numpy.ndarray'>


In [11]:
import numpy as np
n2 = np.array([[20,10,100],[40,30,60]])
print(n2)
print(type(n2))
print(n2.dtype)


[[ 20  10 100]
 [ 40  30  60]]
<class 'numpy.ndarray'>
int32


In [13]:
n3=np.zeros((1,2))
print(n3)
n4=np.ones((4,5))
print(n4)

[[0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
n5=np.full((3,3),10)
print(n5)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [15]:
n6=np.arange(10,20)
print(n6)

[10 11 12 13 14 15 16 17 18 19]


In [16]:
n7=np.arange(20,50,5)
print(n7)
n8=np.arange(20,10,-1)
print(n8)

[20 25 30 35 40 45]
[20 19 18 17 16 15 14 13 12 11]


In [19]:
n9=np.random.randint(1,100,5)
print(n9)
print()
n10=np.random.randint(0,10,10)
print(n10)

[95 93 17 63 75]

[4 3 3 4 4 4 7 1 6 8]


In [20]:
n11=np.array([[20,10,20,30,50],[40,30,20,30,10]])
print(n11.shape)

(2, 5)


In [21]:
n11.shape=(5,2)
print(n11)

[[20 10]
 [20 30]
 [50 40]
 [30 20]
 [30 10]]


In [24]:
n11=np.array([20,10,20,30,50])
n12=np.array([40,30,20,30,10])
x=np.vstack((n11,n12))
print(x)

[[20 10 20 30 50]
 [40 30 20 30 10]]


In [26]:
print(np.hstack((n11,n12)))

[20 10 20 30 50 40 30 20 30 10]


In [27]:
print(np.column_stack((n11,n12)))

[[20 40]
 [10 30]
 [20 20]
 [30 30]
 [50 10]]


In [29]:
n11=np.array([20,10,20,30,50])
n12=np.array([40,30,20,30,10,100,90])
print(np.intersect1d(n1,n2))

[10 20 30]


In [31]:
print(np.setdiff1d(n2,n1))

[ 40  60 100]


In [34]:
n11=np.array([20,10,20,30,50])
n12=np.array([40,30,20,30,10])
print(np.sum([n11,n12]))

260


In [35]:
print(np.sum([n11,n12],axis=0))

[60 40 40 60 60]


In [36]:
print(np.sum([n11,n12],axis=1))

[130 130]


In [37]:
n11=np.array([20,10,20,30,50])
n11=n11+1
print(n11)

[21 11 21 31 51]


In [38]:
n11=np.array([20,10,20,30,50])
n11-=5
print(n11)

[15  5 15 25 45]


In [39]:
n11*=10
print(n11)

[150  50 150 250 450]


In [40]:
np.mean(n11)

210.0

In [42]:
np.median(n11)

150.0

In [43]:
np.std(n11)

135.64659966250537

In [44]:
np.save('my_np',n11)

In [48]:
x=np.load('my_npy')

FileNotFoundError: [Errno 2] No such file or directory: 'my_npy'