In [1]:
import numpy as np

create an empty array of 20 0 s and replace 4th object with 5

In [4]:
a=np.zeros(20)
a[3]=5
a

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])


create an empty array of 20 1 s and store it as a varicalbe named array_master copy the same array into another variable named array_copy

In [9]:
array_master=np.ones(20)
array_master
array_copy=array_master.copy()
array_copy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

create an array 30 ones and broadcast all the ones to value 100

In [11]:
a=np.ones(30)
a[:]=100
a

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

create an array from 21 and 31

In [13]:
arr=np.arange(21,32)
arr

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [14]:
arr2=np.arange(11,22)
arr2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [16]:
arr-arr2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

create an array of even nums

In [21]:
eve=np.arange(2,11,2)
eve

array([ 2,  4,  6,  8, 10])

In [22]:
eve1=np.arange(22,31,2)
eve1

array([22, 24, 26, 28, 30])

use the 2 arrays as rows and create a matrix 

In [23]:
np.stack((eve,eve1))

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])


use the 2 arrays as rows and create a matrix

In [24]:
np.column_stack((eve,eve1))

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

ccreate 5*6 natrix from 0 to 29 and retrive values intersection 2nd row and 3rd column

In [27]:
arr=np.arange(30).reshape(5,6)
arr
arr[1,2]

8

create identity matrix of shape 10*10 and replace the 0's with value 21

In [34]:
ide=np.eye(10)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
ide[ide==0]=21
ide

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

In [36]:
ide.shape

(10, 10)

random set of nums between 0 and 1

In [72]:
ar=np.random.rand(10)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

boolean array output where all values >0.2 are true rest are marked as false

In [73]:
ar>0.2

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

array of 5*2 random nums sampled from standard normal distribution

In [43]:
np.random.rand(10).reshape(5,2)

array([[0.11909533, 0.46057756],
       [0.76224366, 0.72847819],
       [0.67740176, 0.70779688],
       [0.73937196, 0.42540038],
       [0.01096778, 0.91690893]])

create an arr of 30 lineraly space points between 0 and 100

np.linspace(0,100,30)


In [48]:
simple=np.arange(0,100).reshape(10,10)
simple

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

retive last 2 rows and first 3 columns values of the above matrix using index and section technique

In [50]:
simple[8:,0:3]

array([[80, 81, 82],
       [90, 91, 92]])

retruve vake 55 from the above matrix using index and section technique

In [54]:
simple[5,5]

55

Retrive all the values from 3rd column in the above matrix

In [56]:
simple[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

retive 4th row value sin above matrix

In [58]:
simple[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

retrive values from 2nd and 4th rows in above matrix

In [59]:
simple[(1,3),:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

Calculate sum of all values in matrix

In [60]:
simple.sum()

4950

In [61]:
simple.std()

28.86607004772212

In [62]:
simple.var()

833.25

In [63]:
simple.mean()

49.5

In [64]:
simple.max()

99

In [65]:
simple.min()

0